### ISSUE TITLE
No valid versions available for capacitor-intents

### ISSUE THREAD

**Issue by iamporus** [IT-MikeS/capacitor-intents#1]
Thanks for the much-needed plugin. However, while installing it via npm:

`npm i capacitor-intents`

I receive following error:
`npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for capacitor-intents`

**Comment by BrOrlandi** [comment]
Try: `npm i capacitor-android-intents`
It's the real name of the package on NPM.
